### ISSUE TITLE
Bug report v6.2.3

### ISSUE THREAD

**Issue by lpgalbraith** [olivierfriard/BORIS#117] opened 2018-04-25 07:34 UTC
Hi,

I have been using BORIS for several weeks but for the past 2 days it has crashed every time I have tried to plot my data. My colleagues have reported similar issues, as well as the screen freezing. I can confirm I'm using the latest version. I would be grateful if this could be sorted quickly as I plan to present this data next week.

Best wishes,

Lorna

**Comment by lpgalbraith** [comment] 2018-04-25 10:38
Not sure whether this is relevant but this error message has come up since I downloaded 6.2.3:

![image](https://user-images.githubusercontent.com/38717006/39240904-1c749ce6-487d-11e8-97c9-28c71334d571.png)

**Comment by olivierfriard** [comment] 2018-04-25 21:11
Hi,
the "sage" colors have been removed from the matplotlib colors list...
The problem is fixed on the development version and I will release a new stable version as soon as possible.
You can fix the problem by replacing the color names by their RGB values in File > Preferences > Plot colors:
darksage by #598556
lightsage by #bcecac
sage by #87ae73

o

**Comment by olivierfriard** [comment] 2018-04-28 07:38
The bug is fixed in v. 6.2.4

**Closed by olivierfriard** 2018-04-28 07:38 UTC
Labels: bug
