### ISSUE TITLE
v. 6.0.6 crashing repeatedly

### ISSUE THREAD

**Issue by tmrupp25** [olivierfriard/BORIS#106] opened 2018-02-21 18:58 UTC
Crashes repeatedly on Windows and Mac when I'm trying to edit an ethogram.

**Comment by olivierfriard** [comment] 2018-02-21 23:44
Hi,
May you be more precise?
What kind of ethogram editing are you trying to do?

**Comment by tmrupp25** [comment] 2018-02-22 01:22
I tried to delete a behavior and then change a few behaviors from state events to point events, but the program kept crashing before I could finish making all the edits.

**Comment by olivierfriard** [comment] 2018-02-22 08:42
I cannot reproduce the problem.
May you send me by email (see About > Contacts on web site) a BORIS project and a detailed procedure to reproduce the crash?
Thank you for your collaboration

**Comment by olivierfriard** [comment] 2018-02-26 12:12
The bug should be fixed in v. 6.1 (available as pre-release for now).
https://github.com/olivierfriard/BORIS/releases/tag/v6.1
Can you confirm this?

Please note that the behavior type must now be selected by double-clicking on the cell.

**Comment by tmrupp25** [comment] 2018-02-26 19:30
Yes, the bug is fixed now. I downloaded v. 6.1 and used the same procedure that had caused the crash in the previous version, and everything worked great.

**Closed** 2018-02-26 21:31 UTC
Labels: bug
